[build]
publish = "."
functions = "netlify/functions"

[[redirects]]
from = "/page2"
to = "/page2.html"
status = 200

[[headers]]
for = "/*"
  [headers.values]
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
